name: CI/CD - Teste com Docker e Cucumber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI_and_CD:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Atualizar repositórios e instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh  # Instalando o Docker sem conflitos com containerd

      - name: Verificar a versão do Docker
        run: docker --version

      - name: Login no Docker Hub (caso necessário)
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Construir a imagem Docker
        run: |
          docker build -t horadoqa/cucumber-login:v1.0.0 .

      - name: Rodar os testes com Cucumber
        run: |
          docker run --rm horadoqa/cucumber-login:v1.0.0 npx cucumber-js

      - name: Push da Imagem para o Docker Hub (Somente se os testes passarem)
        run: |
          docker push horadoqa/cucumber-login:v1.0.0 
