name: Teste com Docker e Cucumber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Você pode mudar para a versão de sua preferência

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Atualizar repositórios e instalar Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io  # Instala o Docker, caso não esteja presente

    - name: Verificar a versão do Docker
      run: docker --version  # Verifica se o Docker foi instalado corretamente

    - name: Login no Docker Hub (caso necessário)
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Construir a imagem Docker
      run: |
        docker build -t horadoqa/cucumber-login:v1.0.0 .

    - name: Rodar os testes com Cucumber
      run: |
        docker run --rm horadoqa/cucumber-login:v1.0.0 npx cucumber-js

    - name: Push da Imagem para o Docker Hub
      run: |
        docker push horadoqa/cucumber-login:v1.0.0
